### ISSUE TITLE
`bundle install` failing on Mac due to capybara-webkit

### ISSUE THREAD

**Issue by IsmailM** [yannickwurm/sequenceserver#152]
`bundle install` is currently failing on a fresh install of Yosemite...

The culprit is ` capybara-webkit (1.4.1) `, which tries to install a native extension using  `qmake`; something that is not installed on Yosemite by default  (see [here](https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit) for more details)...

Installing Qmake ( `brew install qt` ) fixes the problem...

If possible, it would be ideal if this dependency was removed in order to make SS easier for everyone to install...

Note: btw, `qmake`  seems to be installed by default on Ubuntu, so it seems that only OS X  has this problem....

**Comment by yeban** [comment]
1. `capybara-webkit` is a development dependency required to run headless integration tests. We can't remove it.
2. Installing from git is not for everybody. gem install does not pull development dependency so 99% of the users are not affected by this.

I feel the solution to this issue is updating the README to:

1. steer users to gem install
2. if for some reason they still want to use git for production (like @guyleonard), use `bundle install --without development` to avoid fetching deps.
3. mention that `qt` needs to be installed in 'install dependencies' section.

@IsmailM do you think you can you take care of this?
